"""Predefined top regions and cities for supported countries."""

TOP_LOCATIONS = {
    "US": {
        "Каліфорнія": ["Лос-Анджелес", "Сан-Франциско", "Сан-Дієго", "Сан-Хосе", "Сакраменто", "Беверлі-Гіллз"],
        "Техас": ["Х'юстон", "Остін", "Даллас", "Сан-Антоніо", "Форт-Верт"],
        "Нью-Йорк": ["Нью-Йорк", "Баффало", "Рочестер", "Олбані", "Сірак'юс"],
        "Флорида": ["Маямі", "Орландо", "Тампа", "Джексонвілл", "Форт-Лодердейл"],
        "Массачусетс": ["Бостон", "Кембридж", "Вустер", "Спрінгфілд", "Ньютон"],
        "Вашингтон": ["Сіетл", "Беллв'ю", "Такома", "Спокан", "Редмонд"],
        "Нью-Джерсі": ["Ньюарк", "Джерсі-Сіті", "Прінстон", "Едісон", "Трентон"],
        "Іллінойс": ["Чикаго", "Нейпервілл", "Еванстон", "Шамбург", "Оук-Брук"],
        "Колорадо": ["Денвер", "Боулдер", "Колорадо-Спрінгс", "Форт-Коллінс", "Орора"],
        "Вірджинія": ["Арлінгтон", "Александрія", "Річмонд", "Вірджинія-Біч", "Ферфакс"],
    },
    "GB": {
        "London": ["London", "Westminster", "Camden", "Islington", "Richmond"],
        "South East England": ["Oxford", "Reading", "Brighton", "Guildford", "Milton Keynes"],
        "East of England": ["Cambridge", "Norwich", "Chelmsford", "Colchester", "Peterborough"],
        "West Midlands": ["Birmingham", "Coventry", "Solihull", "Wolverhampton", "Warwick"],
        "North West England": ["Manchester", "Liverpool", "Chester", "Warrington", "Preston"],
        "South West England": ["Bristol", "Bath", "Bournemouth", "Exeter", "Cheltenham"],
        "Yorkshire and the Humber": ["Leeds", "Sheffield", "York", "Harrogate", "Hull"],
        "East Midlands": ["Nottingham", "Leicester", "Derby", "Northampton", "Lincoln"],
        "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Stirling"],
        "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor"],
    },
    "DE": {
        "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Ingolstadt"],
        "North Rhine-Westphalia": ["Cologne", "Dusseldorf", "Dortmund", "Essen", "Bonn"],
        "Baden-Wurttemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg"],
        "Hesse": ["Frankfurt", "Wiesbaden", "Darmstadt", "Kassel", "Offenbach"],
        "Berlin": ["Berlin", "Potsdam", "Cottbus", "Oranienburg", "Falkensee"],
        "Hamburg": ["Hamburg", "Altona", "Wandsbek", "Harburg", "Bergedorf"],
        "Lower Saxony": ["Hanover", "Braunschweig", "Osnabruck", "Oldenburg", "Göttingen"],
        "Rhineland-Palatinate": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Worms"],
        "Schleswig-Holstein": ["Kiel", "Lubeck", "Flensburg", "Neumunster", "Norderstedt"],
        "Saxony": ["Leipzig", "Dresden", "Chemnitz", "Zwickau", "Görlitz"],
    },
    "FR": {
        "Île-de-France": ["Paris", "Boulogne-Billancourt", "Versailles", "Saint-Denis", "Nanterre"],
        "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Annecy", "Chambery", "Clermont-Ferrand"],
        "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Cannes", "Aix-en-Provence", "Toulon"],
        "Occitanie": ["Toulouse", "Montpellier", "Nimes", "Perpignan", "Montauban"],
        "Nouvelle-Aquitaine": ["Bordeaux", "La Rochelle", "Bayonne", "Pau", "Limoges"],
        "Hauts-de-France": ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkerque"],
        "Grand Est": ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"],
        "Pays de la Loire": ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "Cholet"],
        "Bretagne": ["Rennes", "Brest", "Lorient", "Vannes", "Quimper"],
        "Normandie": ["Rouen", "Caen", "Le Havre", "Cherbourg", "Évreux"],
    },
    "ES": {
        "Community of Madrid": ["Madrid", "Alcobendas", "Pozuelo de Alarcón", "Majadahonda", "Las Rozas"],
        "Catalonia": ["Barcelona", "Girona", "Tarragona", "Lleida", "Sabadell"],
        "Basque Country": ["Bilbao", "San Sebastian", "Vitoria-Gasteiz", "Barakaldo", "Getxo"],
        "Navarre": ["Pamplona", "Tudela", "Barañáin", "Estella-Lizarra", "Tafalla"],
        "Balearic Islands": ["Palma", "Ibiza Town", "Calvia", "Manacor", "Inca"],
        "Valencian Community": ["Valencia", "Alicante", "Benidorm", "Castellon de la Plana", "Elche"],
        "Andalusia": ["Seville", "Malaga", "Marbella", "Granada", "Cordoba"],
        "Aragon": ["Zaragoza", "Huesca", "Teruel", "Calatayud", "Utebo"],
        "Canary Islands": ["Las Palmas de Gran Canaria", "Santa Cruz de Tenerife", "La Laguna", "Arrecife", "Puerto de la Cruz"],
        "Galicia": ["A Coruna", "Vigo", "Santiago de Compostela", "Ourense", "Pontevedra"],
    },
    "IT": {
        "Lombardy": ["Milan", "Bergamo", "Brescia", "Monza", "Como"],
        "Lazio": ["Rome", "Latina", "Viterbo", "Frosinone", "Civitavecchia"],
        "Emilia-Romagna": ["Bologna", "Parma", "Modena", "Ravenna", "Reggio Emilia"],
        "Veneto": ["Venice", "Verona", "Padua", "Vicenza", "Treviso"],
        "Piedmont": ["Turin", "Novara", "Alessandria", "Asti", "Cuneo"],
        "Tuscany": ["Florence", "Pisa", "Siena", "Lucca", "Prato"],
        "Campania": ["Naples", "Salerno", "Caserta", "Benevento", "Avellino"],
        "Liguria": ["Genoa", "La Spezia", "Savona", "Sanremo", "Imperia"],
        "Trentino-Alto Adige": ["Bolzano", "Trento", "Merano", "Rovereto", "Bressanone"],
        "Friuli-Venezia Giulia": ["Trieste", "Udine", "Pordenone", "Gorizia", "Monfalcone"],
    },
    "NL": {
        "North Holland": ["Amsterdam", "Haarlem", "Amstelveen", "Hilversum", "Alkmaar"],
        "South Holland": ["Rotterdam", "The Hague", "Leiden", "Delft", "Dordrecht"],
        "Utrecht": ["Utrecht", "Amersfoort", "Zeist", "Nieuwegein", "Houten"],
        "North Brabant": ["Eindhoven", "Tilburg", "Breda", "'s-Hertogenbosch", "Helmond"],
        "Gelderland": ["Arnhem", "Nijmegen", "Apeldoorn", "Ede", "Wageningen"],
        "Overijssel": ["Enschede", "Zwolle", "Deventer", "Hengelo", "Almelo"],
        "Limburg": ["Maastricht", "Sittard", "Venray", "Heerlen", "Roermond"],
        "Groningen": ["Groningen", "Delfzijl", "Veendam", "Hoogezand", "Stadskanaal"],
        "Flevoland": ["Almere", "Lelystad", "Dronten", "Emmeloord", "Zeewolde"],
        "Zeeland": ["Middelburg", "Vlissingen", "Goes", "Terneuzen", "Zierikzee"],
    },
    "PL": {
        "Masovian Voivodeship": ["Warsaw", "Radom", "Płock", "Siedlce", "Ostrołęka"],
        "Silesian Voivodeship": ["Katowice", "Krakow", "Gliwice", "Tychy", "Bielsko-Biała"],
        "Lesser Poland Voivodeship": ["Krakow", "Tarnow", "Nowy Sącz", "Zakopane", "Oświęcim"],
        "Greater Poland Voivodeship": ["Poznan", "Kalisz", "Konin", "Leszno", "Gniezno"],
        "Lower Silesian Voivodeship": ["Wroclaw", "Legnica", "Wałbrzych", "Jelenia Góra", "Lubin"],
        "Pomeranian Voivodeship": ["Gdansk", "Gdynia", "Sopot", "Slupsk", "Tczew"],
        "Łódź Voivodeship": ["Lodz", "Piotrków Trybunalski", "Pabianice", "Tomaszow Mazowiecki", "Zgierz"],
        "West Pomeranian Voivodeship": ["Szczecin", "Koszalin", "Stargard", "Kołobrzeg", "Świnoujście"],
        "Kuyavian-Pomeranian Voivodeship": ["Bydgoszcz", "Torun", "Wloclawek", "Grudziadz", "Inowroclaw"],
        "Podkarpackie Voivodeship": ["Rzeszow", "Przemysl", "Krosno", "Tarnobrzeg", "Mielec"],
    },
    "UA": {
        "Kyiv": ["Kyiv", "Brovary", "Bucha", "Irpin", "Vyshneve"],
        "Dnipropetrovsk Oblast": ["Dnipro", "Kryvyi Rih", "Kamianske", "Pavlohrad", "Nikopol"],
        "Lviv Oblast": ["Lviv", "Drohobych", "Chervonohrad", "Stryi", "Truskavets"],
        "Odesa Oblast": ["Odesa", "Chornomorsk", "Izmail", "Bilhorod-Dnistrovskyi", "Yuzhne"],
        "Kyiv Oblast": ["Bila Tserkva", "Brovary", "Bucha", "Irpin", "Vyshhorod"],
        "Kharkiv Oblast": ["Kharkiv", "Chuhuiv", "Izium", "Lozova", "Balakliia"],
        "Vinnytsia Oblast": ["Vinnytsia", "Zhmerynka", "Mohyliv-Podilskyi", "Khmilnyk", "Haisyn"],
        "Ivano-Frankivsk Oblast": ["Ivano-Frankivsk", "Kalush", "Kolomyia", "Yaremche", "Nadvirna"],
        "Zakarpattia Oblast": ["Uzhhorod", "Mukachevo", "Khust", "Berehove", "Vynohradiv"],
        "Poltava Oblast": ["Poltava", "Kremenchuk", "Lubny", "Myrhorod", "Horishni Plavni"],
    },
}
